apiVersion: v1
kind: Service
metadata:
  name: php-host
  labels:
    app: php-host
spec:
  type: NodePort
  ports:
    - port: 9000
      nodePort: 32000
      protocol: TCP
  selector:
    app: php-host
