apiVersion: v1
kind: Service
metadata:
  name: redis-host
  labels:
    app: redis-host
spec:
  type: NodePort
  ports:
    - port: 6379
      nodePort: 30006
      protocol: TCP
  selector:
    app: redis-host
